### ISSUE TITLE
Don't allow more than one definition in the Scheme for the same env

### ISSUE THREAD

**Issue by CristhianMotoche** [stackbuilders/dotenv-hs#75]
Currently, the user can define multiple configurations for the same env. However, the system has the following behaviour: it matches the types with the value and then type checks for all the types specified.

For instance, 
```yml
- name: PORT
  type: integer
  required: true
- name: PORT
  type: bool
  required: true
```

`PORT` will be evaluated as a bool and integer, then dotenv will always fail.
Although, it would be better to display an error message.
